//! Platform constants and parameters for raspi4-aarch64.
//! Generated by build.rs, DO NOT edit!

/// Stack size of each task.
pub const TASK_STACK_SIZE: usize = 0x40000;
/// Number of timer ticks per second (Hz). A timer tick may contain several timer
/// interrupts.
pub const TICKS_PER_SEC: usize = 100;
/// Architecture identifier.
pub const ARCH: &str = "aarch64";
/// Platform identifier.
pub const PLATFORM: &str = "phytiumpi-aarch64";
/// Base address of the whole physical memory.
pub const PHYS_MEMORY_BASE: usize = 0x8000_0000;
/// Size of the whole physical memory.
pub const PHYS_MEMORY_SIZE: usize = 0x8000_0000;
/// Base physical address of the kernel image.
pub const KERNEL_BASE_PADDR: usize = 0x9010_0000;
/// Base virtual address of the kernel image.
pub const KERNEL_BASE_VADDR: usize = 0xffff_0000_9010_0000;
/// Linear mapping offset, for quick conversions between physical and virtual
/// addresses.
pub const PHYS_VIRT_OFFSET: usize = 0xffff_0000_0000_0000;
/// MMIO regions with format (`base_paddr`, `size`).
pub const MMIO_REGIONS: &[(usize, usize)] = &[
    (0x2800_C000, 0x1000),
    (0x2800_D000, 0x1000),
    (0x2800_E000, 0x1000),
    (0x2800_F000, 0x1000),
    (0xFE20_1000, 0x1000),
    (0xFF84_1000, 0x8000),
    (0x3000_0000,0x800_0000),    
    (0x4000_0000,0x4000_0000), 
    (0x10_0000_0000, 0x20_0000_0000),
];

pub const VIRTIO_MMIO_REGIONS: &[(usize, usize)] = &[
];
/// UART Address
pub const UART_PADDR: usize = 0x2800_D000;

pub const UART_IRQ_NUM: usize = 24;
/// GIC Address
pub const GICC_PADDR: usize = 0xFF84_2000;

pub const GICD_PADDR: usize = 0xFF84_1000;
/// Number of CPUs
pub const SMP: usize = 1;
